<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAWTM5RN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAWTM5RN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAWTM5RN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAWTM5RN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAWTM5RN\App_KernelDevDebugContainer([
    'container.build_hash' => 'AWTM5RN',
    'container.build_id' => 'd2aad4b8',
    'container.build_time' => 1606064638,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAWTM5RN');
