<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAru5YTA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAru5YTA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAru5YTA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAru5YTA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAru5YTA\App_KernelDevDebugContainer([
    'container.build_hash' => 'Aru5YTA',
    'container.build_id' => 'c2658a6f',
    'container.build_time' => 1606064459,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAru5YTA');
